"""SQLAlchemy ORM models for HiveMind.

Tables:
- pending_contributions  — inbound knowledge queued for user approval (PII-stripped)
- knowledge_items        — approved knowledge in the commons (with vector embeddings)
- deployment_config      — key/value store for deployment metadata (e.g. pinned model revision)

Design decisions:
- All tables carry org_id for namespace isolation (ACL-01)
- Knowledge provenance fields (source_agent_id, contributed_at, content_hash, etc.)
  are set on INSERT and never updated — immutable per KM-01
- content_hash is SHA-256 of the stripped content
- Unique constraint on (content_hash, org_id) prevents intra-org duplicates while
  allowing two orgs to contribute identical knowledge (pitfall 4 from research)
- embedding column uses VECTOR(384) matching all-MiniLM-L6-v2 output dimensions
- HNSW index created at table creation time (before any data) to avoid table-lock
  during a future online re-index
"""

import datetime
import enum
import uuid

from pgvector.sqlalchemy import VECTOR
from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    Float,
    Index,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class KnowledgeCategory(str, enum.Enum):
    """Controlled vocabulary for classifying knowledge items (KM-04)."""

    bug_fix = "bug_fix"
    config = "config"
    domain_expertise = "domain_expertise"
    workaround = "workaround"
    pricing_data = "pricing_data"
    regulatory_rule = "regulatory_rule"
    tooling = "tooling"
    reasoning_trace = "reasoning_trace"
    failed_approach = "failed_approach"
    version_workaround = "version_workaround"
    general = "general"


class Base(DeclarativeBase):
    """Shared declarative base for all ORM models."""

    pass


class PendingContribution(Base):
    """Inbound knowledge waiting for user approval.

    Content is PII-stripped before being written here (TRUST-01).  The record
    is created by the add_knowledge MCP tool and consumed by the CLI review
    command.  On approval it becomes a KnowledgeItem; on rejection it is
    deleted.
    """

    __tablename__ = "pending_contributions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    # Namespace isolation (ACL-01)
    org_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)

    # Immutable provenance (KM-01)
    source_agent_id: Mapped[str] = mapped_column(String(255), nullable=False)
    run_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    content: Mapped[str] = mapped_column(Text, nullable=False)  # already PII-stripped
    content_hash: Mapped[str] = mapped_column(
        String(64), nullable=False
    )  # SHA-256 of stripped content

    # Knowledge classification (KM-04)
    category: Mapped[KnowledgeCategory] = mapped_column(
        Enum(KnowledgeCategory, name="knowledgecategory"), nullable=False
    )

    # Quality signals
    confidence: Mapped[float] = mapped_column(Float, default=0.8, nullable=False)

    # Framework/language metadata (KM-04)
    framework: Mapped[str | None] = mapped_column(String(100), nullable=True)
    language: Mapped[str | None] = mapped_column(String(50), nullable=True)
    version: Mapped[str | None] = mapped_column(String(50), nullable=True)
    tags: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # Timestamps
    contributed_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=datetime.datetime.utcnow,
    )

    # Safety
    is_sensitive_flagged: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False
    )


class KnowledgeItem(Base):
    """Approved knowledge in the commons.

    Created from PendingContribution on user approval.  Provenance fields
    (source_agent_id, contributed_at, org_id, category, content_hash) are
    copied from the pending record and are immutable (KM-01).

    The embedding column holds a 384-dimensional vector generated by
    all-MiniLM-L6-v2 (KM-08).  The HNSW index enables approximate nearest-
    neighbour cosine search without a full table scan.
    """

    __tablename__ = "knowledge_items"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    # Namespace isolation (ACL-01)
    org_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    is_public: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False
    )  # False = private namespace only

    # Immutable provenance (KM-01)
    source_agent_id: Mapped[str] = mapped_column(String(255), nullable=False)
    run_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)

    # Knowledge classification (KM-04)
    category: Mapped[KnowledgeCategory] = mapped_column(
        Enum(KnowledgeCategory, name="knowledgecategory"), nullable=False
    )

    # Quality signals
    confidence: Mapped[float] = mapped_column(Float, default=0.8, nullable=False)

    # Framework/language metadata (KM-04)
    framework: Mapped[str | None] = mapped_column(String(100), nullable=True)
    language: Mapped[str | None] = mapped_column(String(50), nullable=True)
    version: Mapped[str | None] = mapped_column(String(50), nullable=True)
    tags: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # Vector embedding (KM-08 — 384 dims for all-MiniLM-L6-v2)
    embedding: Mapped[list | None] = mapped_column(VECTOR(384), nullable=True)

    # Timestamps — contributed_at is immutable provenance copied from pending
    contributed_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    approved_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=datetime.datetime.utcnow,
    )

    __table_args__ = (
        # Prevents intra-org duplicates; allows same content across orgs (pitfall 4)
        UniqueConstraint("content_hash", "org_id", name="uq_knowledge_items_hash_org"),
        # HNSW index for cosine similarity search (created before data to avoid lock)
        Index(
            "ix_knowledge_items_embedding_hnsw",
            "embedding",
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
        # Composite index for the common search filter pattern
        Index(
            "ix_knowledge_items_org_public",
            "org_id",
            "is_public",
        ),
    )


class DeploymentConfig(Base):
    """Key/value store for deployment-time configuration.

    Used primarily to pin the embedding model name and HuggingFace revision
    hash at first startup (KM-08).  This allows future migrations to detect
    model version changes and trigger re-embedding if needed.

    Example keys:
    - embedding_model_name    → "sentence-transformers/all-MiniLM-L6-v2"
    - embedding_model_revision → "<git-commit-hash>"
    - schema_version           → "1"
    """

    __tablename__ = "deployment_config"

    key: Mapped[str] = mapped_column(String(255), primary_key=True)
    value: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=datetime.datetime.utcnow,
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=datetime.datetime.utcnow,
        onupdate=datetime.datetime.utcnow,
    )
