// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetKnowledgeItemData, GetKnowledgeItemErrors, GetKnowledgeItemResponses, HealthData, HealthResponses, ReportOutcomeData, ReportOutcomeErrors, ReportOutcomeResponses, SearchKnowledgeData, SearchKnowledgeErrors, SearchKnowledgeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health
 *
 * Simple health check endpoint for load balancers and readiness probes.
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>) => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Semantic search over the knowledge commons
 *
 * Embeds the query text and performs a cosine similarity search over your organisation's private namespace plus the public commons. Results are deduplicated by content hash with private items prioritised.
 */
export const searchKnowledge = <ThrowOnError extends boolean = false>(options: Options<SearchKnowledgeData, ThrowOnError>) => (options.client ?? client).get<SearchKnowledgeResponses, SearchKnowledgeErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/api/v1/knowledge/search',
    ...options
});

/**
 * Fetch a knowledge item by UUID
 *
 * Returns full content for a specific knowledge item. Includes content hash integrity verification (SEC-02). Returns integrity_verified=True if the hash matches, or integrity_warning if a mismatch is detected.
 */
export const getKnowledgeItem = <ThrowOnError extends boolean = false>(options: Options<GetKnowledgeItemData, ThrowOnError>) => (options.client ?? client).get<GetKnowledgeItemResponses, GetKnowledgeItemErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/api/v1/knowledge/{item_id}',
    ...options
});

/**
 * Report a usage outcome for a knowledge item
 *
 * Records whether a knowledge item helped solve a problem or did not help. Used to compute quality signals for the knowledge commons (QI-01, QI-02). Deduplication by run_id ensures idempotency on retries.
 */
export const reportOutcome = <ThrowOnError extends boolean = false>(options: Options<ReportOutcomeData, ThrowOnError>) => (options.client ?? client).post<ReportOutcomeResponses, ReportOutcomeErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/api/v1/outcomes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
