// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * KnowledgeItemResponse
 *
 * Response body for GET /knowledge/{item_id} — full content.
 */
export type KnowledgeItemResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Content
     */
    content: string;
    /**
     * Category
     */
    category: string;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Framework
     */
    framework: string | null;
    /**
     * Language
     */
    language: string | null;
    /**
     * Version
     */
    version: string | null;
    /**
     * Tags
     */
    tags: {
        [key: string]: unknown;
    } | null;
    /**
     * Org Attribution
     */
    org_attribution: string;
    /**
     * Contributed At
     */
    contributed_at: string;
    /**
     * Integrity Verified
     */
    integrity_verified?: boolean | null;
    /**
     * Integrity Warning
     */
    integrity_warning?: string | null;
};

/**
 * KnowledgeSearchResponse
 *
 * Response body for GET /knowledge/search.
 */
export type KnowledgeSearchResponse = {
    /**
     * Results
     */
    results: Array<KnowledgeSearchResult>;
    /**
     * Total Found
     */
    total_found: number;
    /**
     * Next Cursor
     */
    next_cursor: string | null;
};

/**
 * KnowledgeSearchResult
 *
 * Single result item in a search response.
 */
export type KnowledgeSearchResult = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Category
     */
    category: string;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Org Attribution
     */
    org_attribution: string;
    /**
     * Relevance Score
     */
    relevance_score: number;
};

/**
 * OutcomeRequest
 *
 * Request body for POST /outcomes.
 */
export type OutcomeRequest = {
    /**
     * Item Id
     *
     * UUID of the knowledge item this outcome applies to
     */
    item_id: string;
    /**
     * Outcome
     *
     * Outcome of using this knowledge item
     */
    outcome: 'solved' | 'did_not_help';
    /**
     * Run Id
     *
     * Optional agent run ID for deduplication and tracing. Strongly recommended — prevents double-counting on retries.
     */
    run_id?: string | null;
};

/**
 * OutcomeResponse
 *
 * Response body for POST /outcomes.
 */
export type OutcomeResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Item Id
     */
    item_id: string;
    /**
     * Outcome
     */
    outcome: string;
    /**
     * Signal Id
     */
    signal_id?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SearchKnowledgeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Query
         *
         * Search query text
         */
        query: string;
        /**
         * Category
         *
         * Optional category filter
         */
        category?: string | null;
        /**
         * Limit
         *
         * Max results (1-50)
         */
        limit?: number;
        /**
         * Cursor
         *
         * Pagination cursor from previous response
         */
        cursor?: string | null;
    };
    url: '/api/v1/knowledge/search';
};

export type SearchKnowledgeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchKnowledgeError = SearchKnowledgeErrors[keyof SearchKnowledgeErrors];

export type SearchKnowledgeResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeSearchResponse;
};

export type SearchKnowledgeResponse = SearchKnowledgeResponses[keyof SearchKnowledgeResponses];

export type GetKnowledgeItemData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/api/v1/knowledge/{item_id}';
};

export type GetKnowledgeItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetKnowledgeItemError = GetKnowledgeItemErrors[keyof GetKnowledgeItemErrors];

export type GetKnowledgeItemResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeItemResponse;
};

export type GetKnowledgeItemResponse = GetKnowledgeItemResponses[keyof GetKnowledgeItemResponses];

export type ReportOutcomeData = {
    body: OutcomeRequest;
    path?: never;
    query?: never;
    url: '/api/v1/outcomes';
};

export type ReportOutcomeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReportOutcomeError = ReportOutcomeErrors[keyof ReportOutcomeErrors];

export type ReportOutcomeResponses = {
    /**
     * Successful Response
     */
    202: OutcomeResponse;
};

export type ReportOutcomeResponse = ReportOutcomeResponses[keyof ReportOutcomeResponses];
